<a href="https://colab.research.google.com/github/Harshita15887/SML/blob/main/Assignment4-2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("/content/train.csv ")

FileNotFoundError: [Errno 2] No such file or directory: '/content/train.csv '

In [3]:
df=pd.read_csv("/content/train.csv")

In [4]:
df

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,794,1,0.5,1,0,1,2,0.8,106,6,...,1222,1890,668,13,4,19,1,1,0,0
1996,1965,1,2.6,1,0,0,39,0.2,187,4,...,915,1965,2032,11,10,16,1,1,1,2
1997,1911,0,0.9,1,1,1,36,0.7,108,8,...,868,1632,3057,9,1,5,1,1,0,3
1998,1512,0,0.9,0,4,1,46,0.1,145,5,...,336,670,869,18,10,19,1,1,1,0
1999,510,1,2.0,1,5,1,45,0.9,168,6,...,483,754,3919,19,4,2,1,1,1,3

In [5]:
print(df)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7
1              1021     1          0.5         1   0       1          53
2               563     1          0.5         1   2       1          41
3               615     1          2.5         0   0       0          10
4              1821     1          1.2         0  13       1          44
...             ...   ...          ...       ...  ..     ...         ...
1995            794     1          0.5         1   0       1           2
1996           1965     1          2.6         1   0       0          39
1997           1911     0          0.9         1   1       1          36
1998           1512     0          0.9         0   4       1          46
1999            510     1          2.0         1   5       1          45

      m_dep  mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2  ...         20       756  2549     9     7
1       0.7        136        3  ...        905      1988  2631    17     3
2       0.9        145        5  ...       1263      1716  2603    11     2
3       0.8        131        6  ...       1216      1786  2769    16     8
4       0.6        141        2  ...       1208      1212  1411     8     2
...     ...        ...      ...  ...        ...       ...   ...   ...   ...
1995    0.8        106        6  ...       1222      1890   668    13     4
1996    0.2        187        4  ...        915      1965  2032    11    10
1997    0.7        108        8  ...        868      1632  3057     9     1
1998    0.1        145        5  ...        336       670   869    18    10
1999    0.9        168        6  ...        483       754  3919    19     4

      talk_time  three_g  touch_screen  wifi  price_range
0            19        0             0     1            1
1             7        1             1     0            2
2             9        1             1     0            2
3            11        1             0     0            2
4            15        1             1     0            1
...         ...      ...           ...   ...          ...
1995         19        1             1     0            0
1996         16        1             1     1            2
1997          5        1             1     0            3
1998         19        1             1     1            0
1999          2        1             1     1            3

[2000 rows x 21 columns]

In [6]:
df.head()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1

In [7]:
df.describe()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
count,2000.000000,2000.0000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,...,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,1238.518500,0.4950,1.522250,0.509500,4.309500,0.521500,32.046500,0.501750,140.249000,4.520500,...,645.108000,1251.515500,2124.213000,12.306500,5.767000,11.011000,0.761500,0.503000,0.507000,1.500000
std,439.418206,0.5001,0.816004,0.500035,4.341444,0.499662,18.145715,0.288416,35.399655,2.287837,...,443.780811,432.199447,1084.732044,4.213245,4.356398,5.463955,0.426273,0.500116,0.500076,1.118314
min,501.000000,0.0000,0.500000,0.000000,0.000000,0.000000,2.000000,0.100000,80.000000,1.000000,...,0.000000,500.000000,256.000000,5.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000
25%,851.750000,0.0000,0.700000,0.000000,1.000000,0.000000,16.000000,0.200000,109.000000,3.000000,...,282.750000,874.750000,1207.500000,9.000000,2.000000,6.000000,1.000000,0.000000,0.000000,0.750000
50%,1226.000000,0.0000,1.500000,1.000000,3.000000,1.000000,32.000000,0.500000,141.000000,4.000000,...,564.000000,1247.000000,2146.500000,12.000000,5.000000,11.000000,1.000000,1.000000,1.000000,1.500000
75%,1615.250000,1.0000,2.200000,1.000000,7.000000,1.000000,48.000000,0.800000,170.000000,7.000000,...,947.250000,1633.000000,3064.500000,16.000000,9.000000,16.000000,1.000000,1.000000,1.000000,2.250000
max,1998.000000,1.0000,3.000000,1.000000,19.000000,1.000000,64.000000,1.000000,200.000000,8.000000,...,1960.000000,1998.000000,3998.000000,19.000000,18.000000,20.000000,1.000000,1.000000,1.000000,3.000000

In [8]:
y=pd['price_range']

TypeError: 'module' object is not subscriptable

In [9]:
y=df['price_range']

In [10]:
print(y)

0       1
1       2
2       2
3       2
4       1
       ..
1995    0
1996    2
1997    3
1998    0
1999    3
Name: price_range, Length: 2000, dtype: int64

In [11]:
print(y.shape)

(2000,)

In [12]:
x=df.drop('price_range',axis=1)

In [13]:
print(x)

      battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  \
0               842     0          2.2         0   1       0           7
1              1021     1          0.5         1   0       1          53
2               563     1          0.5         1   2       1          41
3               615     1          2.5         0   0       0          10
4              1821     1          1.2         0  13       1          44
...             ...   ...          ...       ...  ..     ...         ...
1995            794     1          0.5         1   0       1           2
1996           1965     1          2.6         1   0       0          39
1997           1911     0          0.9         1   1       1          36
1998           1512     0          0.9         0   4       1          46
1999            510     1          2.0         1   5       1          45

      m_dep  mobile_wt  n_cores  pc  px_height  px_width   ram  sc_h  sc_w  \
0       0.6        188        2   2         20       756  2549     9     7
1       0.7        136        3   6        905      1988  2631    17     3
2       0.9        145        5   6       1263      1716  2603    11     2
3       0.8        131        6   9       1216      1786  2769    16     8
4       0.6        141        2  14       1208      1212  1411     8     2
...     ...        ...      ...  ..        ...       ...   ...   ...   ...
1995    0.8        106        6  14       1222      1890   668    13     4
1996    0.2        187        4   3        915      1965  2032    11    10
1997    0.7        108        8   3        868      1632  3057     9     1
1998    0.1        145        5   5        336       670   869    18    10
1999    0.9        168        6  16        483       754  3919    19     4

      talk_time  three_g  touch_screen  wifi
0            19        0             0     1
1             7        1             1     0
2             9        1             1     0
3            11        1             0     0
4            15        1             1     0
...         ...      ...           ...   ...
1995         19        1             1     0
1996         16        1             1     1
1997          5        1             1     0
1998         19        1             1     1
1999          2        1             1     1

[2000 rows x 20 columns]

In [14]:
xx=x-x.min/x.max-x.min
print(xx)

TypeError: unsupported operand type(s) for /: 'method' and 'method'

In [15]:
xx=(x-x.min())/(x.max()-x.min())
print(xx)

      battery_power  blue  clock_speed  dual_sim        fc  four_g  \
0          0.227789   0.0         0.68       0.0  0.052632     0.0
1          0.347361   1.0         0.00       1.0  0.000000     1.0
2          0.041416   1.0         0.00       1.0  0.105263     1.0
3          0.076152   1.0         0.80       0.0  0.000000     0.0
4          0.881764   1.0         0.28       0.0  0.684211     1.0
...             ...   ...          ...       ...       ...     ...
1995       0.195725   1.0         0.00       1.0  0.000000     1.0
1996       0.977956   1.0         0.84       1.0  0.000000     0.0
1997       0.941884   0.0         0.16       1.0  0.052632     1.0
1998       0.675351   0.0         0.16       0.0  0.210526     1.0
1999       0.006012   1.0         0.60       1.0  0.263158     1.0

      int_memory     m_dep  mobile_wt   n_cores    pc  px_height  px_width  \
0       0.080645  0.555556   0.900000  0.142857  0.10   0.010204  0.170895
1       0.822581  0.666667   0.466667  0.285714  0.30   0.461735  0.993324
2       0.629032  0.888889   0.541667  0.571429  0.30   0.644388  0.811749
3       0.129032  0.777778   0.425000  0.714286  0.45   0.620408  0.858478
4       0.677419  0.555556   0.508333  0.142857  0.70   0.616327  0.475300
...          ...       ...        ...       ...   ...        ...       ...
1995    0.000000  0.777778   0.216667  0.714286  0.70   0.623469  0.927904
1996    0.596774  0.111111   0.891667  0.428571  0.15   0.466837  0.977971
1997    0.548387  0.666667   0.233333  1.000000  0.15   0.442857  0.755674
1998    0.709677  0.000000   0.541667  0.571429  0.25   0.171429  0.113485
1999    0.693548  0.888889   0.733333  0.714286  0.80   0.246429  0.169559

           ram      sc_h      sc_w  talk_time  three_g  touch_screen  wifi
0     0.612774  0.285714  0.388889   0.944444      0.0           0.0   1.0
1     0.634687  0.857143  0.166667   0.277778      1.0           1.0   0.0
2     0.627205  0.428571  0.111111   0.388889      1.0           1.0   0.0
3     0.671566  0.785714  0.444444   0.500000      1.0           0.0   0.0
4     0.308658  0.214286  0.111111   0.722222      1.0           1.0   0.0
...        ...       ...       ...        ...      ...           ...   ...
1995  0.110102  0.571429  0.222222   0.944444      1.0           1.0   0.0
1996  0.474613  0.428571  0.555556   0.777778      1.0           1.0   1.0
1997  0.748530  0.285714  0.055556   0.166667      1.0           1.0   0.0
1998  0.163816  0.928571  0.555556   0.944444      1.0           1.0   1.0
1999  0.978888  1.000000  0.222222   0.000000      1.0           1.0   1.0

[2000 rows x 20 columns]

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
x_train,x_test,y_train,y_test=train_test_split(xx,y,test_size=0.2,random_state=30)
print(x_train,x_test,y_train,y_test)

      battery_power  blue  clock_speed  dual_sim        fc  four_g  \
1572       0.263193   0.0         0.00       1.0  0.315789     0.0
1442       0.315297   0.0         0.00       1.0  0.263158     0.0
1516       0.387442   1.0         0.56       1.0  0.684211     1.0
259        0.706747   1.0         0.44       1.0  0.315789     1.0
945        0.221109   0.0         0.24       0.0  0.000000     1.0
...             ...   ...          ...       ...       ...     ...
500        0.519038   1.0         0.00       1.0  0.052632     0.0
1837       0.321977   0.0         0.04       1.0  0.000000     1.0
941        0.161657   0.0         0.00       1.0  0.000000     1.0
421        0.452238   0.0         0.68       1.0  0.315789     0.0
1829       0.376754   0.0         0.48       1.0  0.210526     1.0

      int_memory     m_dep  mobile_wt   n_cores    pc  px_height  px_width  \
1572    0.225806  0.222222   0.700000  1.000000  0.70   0.064286  0.717623
1442    0.822581  0.444444   0.966667  0.571429  0.35   0.053571  0.058745
1516    0.645161  0.000000   0.175000  0.857143  0.85   0.042347  0.210948
259     0.064516  0.444444   0.683333  0.714286  0.85   0.091327  0.706943
945     0.709677  0.222222   0.108333  0.714286  0.00   0.418367  0.578104
...          ...       ...        ...       ...   ...        ...       ...
500     0.838710  0.000000   0.200000  1.000000  0.80   0.296429  0.166889
1837    0.693548  0.000000   0.416667  0.428571  0.55   0.483673  0.470628
941     0.500000  0.222222   0.125000  0.142857  0.05   0.809694  0.773698
421     0.887097  0.222222   0.033333  0.285714  0.85   0.048980  0.568758
1829    0.741935  0.222222   0.683333  0.714286  0.40   0.606122  0.966622

           ram      sc_h      sc_w  talk_time  three_g  touch_screen  wifi
1572  0.765901  0.142857  0.000000   0.111111      0.0           0.0   1.0
1442  0.428915  0.571429  0.555556   0.777778      0.0           1.0   0.0
1516  0.587921  0.142857  0.222222   0.277778      1.0           0.0   0.0
259   0.827365  0.285714  0.055556   0.055556      1.0           1.0   1.0
945   0.818012  0.214286  0.000000   0.944444      1.0           1.0   0.0
...        ...       ...       ...        ...      ...           ...   ...
500   0.240246  0.142857  0.055556   1.000000      0.0           0.0   1.0
1837  0.479957  0.000000  0.166667   0.222222      1.0           0.0   1.0
941   0.016034  1.000000  0.555556   0.111111      1.0           0.0   0.0
421   0.597541  0.785714  0.777778   0.444444      1.0           1.0   0.0
1829  0.002405  0.214286  0.000000   0.555556      1.0           0.0   0.0

[1600 rows x 20 columns]       battery_power  blue  clock_speed  dual_sim        fc  four_g  \
1856       0.858383   0.0         0.84       0.0  0.315789     0.0
364        0.277221   1.0         0.84       0.0  0.000000     0.0
1948       0.164997   0.0         0.36       0.0  0.000000     0.0
1458       0.579158   0.0         0.00       0.0  0.526316     1.0
609        0.474950   0.0         0.84       0.0  0.052632     1.0
...             ...   ...          ...       ...       ...     ...
1163       0.954576   1.0         0.60       0.0  0.578947     0.0
572        0.801603   1.0         0.00       0.0  0.684211     1.0
1105       0.674015   1.0         0.80       1.0  0.578947     0.0
1903       0.574482   1.0         0.36       0.0  0.052632     0.0
481        0.798931   1.0         0.08       0.0  0.052632     1.0

      int_memory     m_dep  mobile_wt   n_cores    pc  px_height  px_width  \
1856    0.193548  1.000000   0.291667  0.428571  0.75   0.314286  0.275033
364     0.548387  0.222222   0.958333  0.428571  0.60   0.095918  0.328438
1948    0.370968  1.000000   0.250000  0.857143  0.70   0.044898  0.139519
1458    0.645161  0.111111   0.091667  0.000000  1.00   0.462755  0.283712
609     0.709677  0.222222   0.183333  0.428571  0.40   0.311735  0.811081
...          ...       ...        ...       ...   ...        ...       ...
1163    0.225806  0.777778   0.883333  1.000000  0.60   0.969898  0.947931
572     0.709677  0.888889   0.291667  0.142857  0.75   0.185714  0.218959
1105    0.725806  0.666667   0.483333  0.142857  0.65   0.060204  0.447263
1903    0.725806  1.000000   0.741667  0.571429  0.10   0.449490  0.588785
481     0.516129  0.000000   0.125000  0.000000  0.15   0.120408  0.510013

           ram      sc_h      sc_w  talk_time  three_g  touch_screen  wifi
1856  0.743453  0.928571  0.000000   0.666667      1.0           0.0   0.0
364   0.324425  0.571429  0.000000   0.666667      0.0           1.0   0.0
1948  0.459113  0.857143  0.277778   0.611111      0.0           1.0   1.0
1458  0.356494  0.500000  0.000000   0.666667      1.0           0.0   0.0
609   0.532603  0.642857  0.166667   0.111111      1.0           1.0   1.0
...        ...       ...       ...        ...      ...           ...   ...
1163  0.408071  0.857143  0.166667   0.611111      0.0           0.0   1.0
572   0.924906  0.428571  0.000000   0.444444      1.0           1.0   0.0
1105  0.168626  0.928571  0.333333   0.166667      0.0           0.0   0.0
1903  0.598343  0.214286  0.388889   0.777778      0.0           0.0   1.0
481   0.920631  0.714286  0.500000   0.333333      1.0           1.0   0.0

[400 rows x 20 columns] 1572    2
1442    1
1516    1
259     3
945     3
       ..
500     0
1837    1
941     0
421     2
1829    0
Name: price_range, Length: 1600, dtype: int64 1856    3
364     0
1948    1
1458    1
609     2
       ..
1163    2
572     3
1105    0
1903    2
481     3
Name: price_range, Length: 400, dtype: int64

In [18]:
import pandas as pd

In [19]:
df=pd.read_csv("/content/housing.csv")

In [20]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [21]:
print(df)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0
1        -122.22     37.86                21.0       7099.0          1106.0
2        -122.24     37.85                52.0       1467.0           190.0
3        -122.25     37.85                52.0       1274.0           235.0
4        -122.25     37.85                52.0       1627.0           280.0
...          ...       ...                 ...          ...             ...
20635    -121.09     39.48                25.0       1665.0           374.0
20636    -121.21     39.49                18.0        697.0           150.0
20637    -121.22     39.43                17.0       2254.0           485.0
20638    -121.32     39.43                18.0       1860.0           409.0
20639    -121.24     39.37                16.0       2785.0           616.0

       population  households  median_income  median_house_value  \
0           322.0       126.0         8.3252            452600.0
1          2401.0      1138.0         8.3014            358500.0
2           496.0       177.0         7.2574            352100.0
3           558.0       219.0         5.6431            341300.0
4           565.0       259.0         3.8462            342200.0
...           ...         ...            ...                 ...
20635       845.0       330.0         1.5603             78100.0
20636       356.0       114.0         2.5568             77100.0
20637      1007.0       433.0         1.7000             92300.0
20638       741.0       349.0         1.8672             84700.0
20639      1387.0       530.0         2.3886             89400.0

      ocean_proximity
0            NEAR BAY
1            NEAR BAY
2            NEAR BAY
3            NEAR BAY
4            NEAR BAY
...               ...
20635          INLAND
20636          INLAND
20637          INLAND
20638          INLAND
20639          INLAND

[20640 rows x 10 columns]

In [22]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [23]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [24]:
target=pd['median_house_value']

TypeError: 'module' object is not subscriptable

In [25]:
target=df['median_house_value']

In [26]:
print(target)

0        452600.0
1        358500.0
2        352100.0
3        341300.0
4        342200.0
           ...
20635     78100.0
20636     77100.0
20637     92300.0
20638     84700.0
20639     89400.0
Name: median_house_value, Length: 20640, dtype: float64

In [31]:
features=df.drop('median_house_value',axis=1)
features=df.drop('ocean_proximity',axis=1)
print(features)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0        -122.23     37.88                41.0        880.0           129.0
1        -122.22     37.86                21.0       7099.0          1106.0
2        -122.24     37.85                52.0       1467.0           190.0
3        -122.25     37.85                52.0       1274.0           235.0
4        -122.25     37.85                52.0       1627.0           280.0
...          ...       ...                 ...          ...             ...
20635    -121.09     39.48                25.0       1665.0           374.0
20636    -121.21     39.49                18.0        697.0           150.0
20637    -121.22     39.43                17.0       2254.0           485.0
20638    -121.32     39.43                18.0       1860.0           409.0
20639    -121.24     39.37                16.0       2785.0           616.0

       population  households  median_income  median_house_value
0           322.0       126.0         8.3252            452600.0
1          2401.0      1138.0         8.3014            358500.0
2           496.0       177.0         7.2574            352100.0
3           558.0       219.0         5.6431            341300.0
4           565.0       259.0         3.8462            342200.0
...           ...         ...            ...                 ...
20635       845.0       330.0         1.5603             78100.0
20636       356.0       114.0         2.5568             77100.0
20637      1007.0       433.0         1.7000             92300.0
20638       741.0       349.0         1.8672             84700.0
20639      1387.0       530.0         2.3886             89400.0

[20640 rows x 9 columns]

In [32]:
normalisation=(features-features.min())/(features.max()-features.min())
print(normalisation)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0       0.211155  0.567481            0.784314     0.022331        0.019863
1       0.212151  0.565356            0.392157     0.180503        0.171477
2       0.210159  0.564293            1.000000     0.037260        0.029330
3       0.209163  0.564293            1.000000     0.032352        0.036313
4       0.209163  0.564293            1.000000     0.041330        0.043296
...          ...       ...                 ...          ...             ...
20635   0.324701  0.737513            0.470588     0.042296        0.057883
20636   0.312749  0.738576            0.333333     0.017676        0.023122
20637   0.311753  0.732200            0.313725     0.057277        0.075109
20638   0.301793  0.732200            0.333333     0.047256        0.063315
20639   0.309761  0.725824            0.294118     0.070782        0.095438

       population  households  median_income  median_house_value
0        0.008941    0.020556       0.539668            0.902266
1        0.067210    0.186976       0.538027            0.708247
2        0.013818    0.028943       0.466028            0.695051
3        0.015555    0.035849       0.354699            0.672783
4        0.015752    0.042427       0.230776            0.674638
...           ...         ...            ...                 ...
20635    0.023599    0.054103       0.073130            0.130105
20636    0.009894    0.018582       0.141853            0.128043
20637    0.028140    0.071041       0.082764            0.159383
20638    0.020684    0.057227       0.094295            0.143713
20639    0.038790    0.086992       0.130253            0.153403

[20640 rows x 9 columns]

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
feature_train,feature_test,target_train,target_test=train_test_split(normalisation,target,test_size=0.2,random_state=30)
print(feature_train,feature_test,target_train,target_test)

       longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
7186    0.614542  0.158342            0.745098     0.015438        0.022346
7686    0.622510  0.147715            0.666667     0.041203        0.046710
6332    0.637450  0.154091            0.450980     0.030953        0.027312
14192   0.725100  0.015940            0.372549     0.055700        0.062849
6611    0.621514  0.174283            1.000000     0.090773        0.078988
...          ...       ...                 ...          ...             ...
500     0.207171  0.564293            1.000000     0.050155        0.065953
12077   0.668327  0.141339            0.019608     0.444275        0.423029
15277   0.698207  0.055260            0.313725     0.069078        0.080230
4517    0.612550  0.159405            0.843137     0.035531        0.059745
5925    0.652390  0.171095            0.254902     0.200265        0.194289

       population  households  median_income  median_house_value
7186     0.019255    0.021871       0.166674            0.269692
7686     0.023599    0.046538       0.281169            0.352784
6332     0.017013    0.030258       0.434332            0.639175
14192    0.049413    0.064463       0.247735            0.247424
6611     0.040108    0.080414       0.372478            0.744329
...           ...         ...            ...                 ...
500      0.024440    0.059530       0.074606            0.285774
12077    0.167073    0.326262       0.395229            0.500825
15277    0.022758    0.066108       0.263327            0.705360
4517     0.039687    0.061174       0.091206            0.265568
5925     0.103590    0.190923       0.347747            0.481856

[16512 rows x 9 columns]        longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
19449   0.330677  0.546227            0.372549     0.081439        0.096834
10452   0.666335  0.097768            0.490196     0.052673        0.057263
18982   0.233068  0.607864            0.215686     0.105041        0.110025
8187    0.621514  0.131775            0.294118     0.101302        0.087834
15759   0.190239  0.555792            1.000000     0.076097        0.114060
...          ...       ...                 ...          ...             ...
12704   0.292829  0.641870            0.333333     0.176840        0.291899
18742   0.200199  0.853348            0.490196     0.055573        0.073091
19142   0.165339  0.614240            0.274510     0.064449        0.064091
1027    0.378486  0.629118            0.294118     0.036650        0.038485
17830   0.249004  0.517535            0.470588     0.046671        0.042986

       population  households  median_income  median_house_value
19449    0.056420    0.099326       0.148743            0.196702
10452    0.026598    0.055747       0.316396            0.563093
18982    0.058410    0.103930       0.282672            0.257114
8187     0.037109    0.092583       0.515634            1.000000
15759    0.039939    0.114948       0.177701            0.874019
...           ...         ...            ...                 ...
12704    0.078478    0.285973       0.178556            0.260620
18742    0.037445    0.075974       0.106178            0.109074
19142    0.039155    0.069890       0.355954            0.324537
1027     0.012108    0.029600       0.186425            0.235465
17830    0.028112    0.044401       0.426498            0.516082

[4128 rows x 9 columns] 7186     145800.0
7686     186100.0
6332     325000.0
14192    135000.0
6611     376000.0
           ...
500      153600.0
12077    257900.0
15277    357100.0
4517     143800.0
5925     248700.0
Name: median_house_value, Length: 16512, dtype: float64 19449    110400.0
10452    288100.0
18982    139700.0
8187     500001.0
15759    438900.0
           ...
12704    141400.0
18742     67900.0
19142    172400.0
1027     129200.0
17830    265300.0
Name: median_house_value, Length: 4128, dtype: float64